from enum import Enum

class ApiError(Enum):
    INVALID_HASHTAG = "INVALID_HASHTAG"
    INVALID_LOCATION = "INVALID_LOCATION"
    INVALID_TEXT = "INVALID_TEXT"
    INVALID_INPUT = "INVALID_INPUT"
    USER_NOT_FOUND = "USER_NOT_FOUND"

class TweepyError(Enum):
    INVALID_USER = 34
    INVALID_HASHTAG = 195